Time::DATE_FORMATS[:default] = "%d.%m.%Y %H:%M"
Time::DATE_FORMATS[:short_text] = "%e %b %Y %H:%M"
Time::DATE_FORMATS[:short_text_with_time] = "%e %b %Y %H:%M"
Time::DATE_FORMATS[:text] = "%e %B %Y"
Time::DATE_FORMATS[:text_with_time] = "%e %B %Y %H:%M"
